[package]
name = "sudoku_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }

argon2 = "0.5" 
rand = "0.8"
rand_core = "0.6"
regex = "1"


